vagrant: make missing minion non-fatal
This makes it easier to add your own VMs to the configuration, as
provisioning will succeed leaving you to authorise the new minion key
with the master.

diff --git a/_vagrant/salt/install b/_vagrant/salt/install
--- a/_vagrant/salt/install
+++ b/_vagrant/salt/install
@@ -29,6 +29,17 @@ SALTSTACK_GPG_KEY='https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/SALT
 SALTSTACK_SOURCES='deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main'
 SALTSTACK_SOURCES_LIST='/etc/apt/sources.list.d/saltstack.list'
 
+cp_if_exists() {
+    local source="$1"
+    local dest="$2"
+
+    if [ -f "$source" ]; then
+        cp "$source" "$dest"
+    else
+        echo "skipping missing file ${source}" >&2
+    fi
+}
+
 echo 'installing saltstack GPG key...'
 curl -s "$SALTSTACK_GPG_KEY" | sudo apt-key add -
 
@@ -62,10 +73,10 @@ if [ -n "$install_minion" ]; then
     apt-get install -y salt-minion -o Dpkg::Options::="--force-confold" >/dev/null
 
     echo 'installing minion configuration and keys...'
-    cp "${root}/minions/${install_minion}"        /etc/salt/minion
-    cp "${root}/minions/${install_minion}.grains" /etc/salt/grains
-    cp "${root}/minions/${install_minion}.pem"    /etc/salt/pki/minion/minion.pem
-    cp "${root}/minions/${install_minion}.pub"    /etc/salt/pki/minion/minion.pub
+    cp_if_exists "${root}/minions/${install_minion}"        /etc/salt/minion
+    cp_if_exists "${root}/minions/${install_minion}.grains" /etc/salt/grains
+    cp_if_exists "${root}/minions/${install_minion}.pem"    /etc/salt/pki/minion/minion.pem
+    cp_if_exists "${root}/minions/${install_minion}.pub"    /etc/salt/pki/minion/minion.pub
 
     echo 'preseeding minion with master key...'
     cp "${root}/master.pub" /etc/salt/pki/minion/minion_master.pub
